# Icons for xfce4-power-profile-plugin

install_data(
  'power-profile-performance-symbolic.svg',
  'power-profile-balanced-symbolic.svg',
  'power-profile-power-saver-symbolic.svg',
  'power-profile-error-symbolic.svg',
  install_dir: get_option('prefix') / get_option('datadir') / 'icons' / 'hicolor' / 'scalable' / 'status',
)
